//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Clinica.Database
{

    [Persistent(@"consulta")]
    public partial class Consulta : XPLiteObject
    {
        int fId;
        [Key]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Medico fMedico;
        [Persistent(@"medico")]
        public Medico Medico
        {
            get { return fMedico; }
            set { SetPropertyValue<Medico>(nameof(Medico), ref fMedico, value); }
        }
        Paciente fPaciente;
        [Persistent(@"paciente")]
        [Association(@"ConsultaReferencesPaciente")]
        public Paciente Paciente
        {
            get { return fPaciente; }
            set { SetPropertyValue<Paciente>(nameof(Paciente), ref fPaciente, value); }
        }
        DateTime fFechahora;
        [Persistent(@"fechahora")]
        public DateTime Fechahora
        {
            get { return fFechahora; }
            set { SetPropertyValue<DateTime>(nameof(Fechahora), ref fFechahora, value); }
        }
        Signosvitales fSignosvitales;
        [Persistent(@"signosvitales")]
        [Association(@"ConsultaReferencesSignosvitales")]
        public Signosvitales Signosvitales
        {
            get { return fSignosvitales; }
            set { SetPropertyValue<Signosvitales>(nameof(Signosvitales), ref fSignosvitales, value); }
        }
        string fObservacion;
        [Size(535)]
        [Persistent(@"observacion")]
        public string Observacion
        {
            get { return fObservacion; }
            set { SetPropertyValue<string>(nameof(Observacion), ref fObservacion, value); }
        }
        string fDiagnostico;
        [Size(535)]
        public string Diagnostico
        {
            get { return fDiagnostico; }
            set { SetPropertyValue<string>(nameof(Diagnostico), ref fDiagnostico, value); }
        }
        string fReceta;
        [Size(535)]
        public string Receta
        {
            get { return fReceta; }
            set { SetPropertyValue<string>(nameof(Receta), ref fReceta, value); }
        }
        Medico fUser;
        [Persistent(@"user")]
        public Medico User
        {
            get { return fUser; }
            set { SetPropertyValue<Medico>(nameof(User), ref fUser, value); }
        }
        Medico fJinx;
        [Persistent(@"jinx")]
        public Medico Jinx
        {
            get { return fJinx; }
            set { SetPropertyValue<Medico>(nameof(Jinx), ref fJinx, value); }
        }
    }

}
