//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Clinica.Database
{

    [Persistent(@"diagnostico")]
    public partial class Diagnostico : XPLiteObject
    {
        int fId;
        [Key]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        int fConsulta;
        [Persistent(@"consulta")]
        public int Consulta
        {
            get { return fConsulta; }
            set { SetPropertyValue<int>(nameof(Consulta), ref fConsulta, value); }
        }
        string fEnfermedad;
        [Size(535)]
        [Persistent(@"enfermedad")]
        public string Enfermedad
        {
            get { return fEnfermedad; }
            set { SetPropertyValue<string>(nameof(Enfermedad), ref fEnfermedad, value); }
        }
        string fObservacion;
        [Size(535)]
        [Persistent(@"observacion")]
        public string Observacion
        {
            get { return fObservacion; }
            set { SetPropertyValue<string>(nameof(Observacion), ref fObservacion, value); }
        }
    }

}
