//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Clinica.Database
{

    [Persistent(@"paciente")]
    public partial class Paciente : XPLiteObject
    {
        int fNum_seguro;
        [Key]
        [Persistent(@"num_seguro")]
        public int Num_seguro
        {
            get { return fNum_seguro; }
            set { SetPropertyValue<int>(nameof(Num_seguro), ref fNum_seguro, value); }
        }
        string fNombre;
        [Size(20)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fApellido;
        [Size(20)]
        [Persistent(@"apellido")]
        public string Apellido
        {
            get { return fApellido; }
            set { SetPropertyValue<string>(nameof(Apellido), ref fApellido, value); }
        }
        string fCedula;
        [Size(14)]
        [Persistent(@"cedula")]
        public string Cedula
        {
            get { return fCedula; }
            set { SetPropertyValue<string>(nameof(Cedula), ref fCedula, value); }
        }
        DateTime fFcha_nac;
        [Persistent(@"fcha_nac")]
        public DateTime Fcha_nac
        {
            get { return fFcha_nac; }
            set { SetPropertyValue<DateTime>(nameof(Fcha_nac), ref fFcha_nac, value); }
        }
        string fTelefono;
        [Size(15)]
        [Persistent(@"telefono")]
        public string Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<string>(nameof(Telefono), ref fTelefono, value); }
        }
        string fNumero_emergencia;
        [Size(15)]
        [Persistent(@"numero_emergencia")]
        public string Numero_emergencia
        {
            get { return fNumero_emergencia; }
            set { SetPropertyValue<string>(nameof(Numero_emergencia), ref fNumero_emergencia, value); }
        }
        [Association(@"ConsultaReferencesPaciente")]
        public XPCollection<Consulta> Consultas { get { return GetCollection<Consulta>(nameof(Consultas)); } }
        [Association(@"SignosvitalesReferencesPaciente")]
        public XPCollection<Signosvitales> SignosvitalesCollection { get { return GetCollection<Signosvitales>(nameof(SignosvitalesCollection)); } }
    }

}
