//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Clinica.Database
{

    [Persistent(@"signosvitales")]
    public partial class Signosvitales : XPLiteObject
    {
        int fId_sv;
        [Key]
        [Persistent(@"id_sv")]
        public int Id_sv
        {
            get { return fId_sv; }
            set { SetPropertyValue<int>(nameof(Id_sv), ref fId_sv, value); }
        }
        Paciente fIdpaciente;
        [Persistent(@"idpaciente")]
        [Association(@"SignosvitalesReferencesPaciente")]
        public Paciente Idpaciente
        {
            get { return fIdpaciente; }
            set { SetPropertyValue<Paciente>(nameof(Idpaciente), ref fIdpaciente, value); }
        }
        float fPeso;
        [Persistent(@"peso")]
        public float Peso
        {
            get { return fPeso; }
            set { SetPropertyValue<float>(nameof(Peso), ref fPeso, value); }
        }
        string fPresion;
        [Size(7)]
        [Persistent(@"presion")]
        public string Presion
        {
            get { return fPresion; }
            set { SetPropertyValue<string>(nameof(Presion), ref fPresion, value); }
        }
        int fTalla;
        [Persistent(@"talla")]
        public int Talla
        {
            get { return fTalla; }
            set { SetPropertyValue<int>(nameof(Talla), ref fTalla, value); }
        }
        string fTemperatura;
        [Size(4)]
        [Persistent(@"temperatura")]
        public string Temperatura
        {
            get { return fTemperatura; }
            set { SetPropertyValue<string>(nameof(Temperatura), ref fTemperatura, value); }
        }
        string fObservaciones;
        [Size(535)]
        [Persistent(@"observaciones")]
        public string Observaciones
        {
            get { return fObservaciones; }
            set { SetPropertyValue<string>(nameof(Observaciones), ref fObservaciones, value); }
        }
        float fEstatura;
        [Persistent(@"estatura")]
        public float Estatura
        {
            get { return fEstatura; }
            set { SetPropertyValue<float>(nameof(Estatura), ref fEstatura, value); }
        }
        [Association(@"ConsultaReferencesSignosvitales")]
        public XPCollection<Consulta> Consultas { get { return GetCollection<Consulta>(nameof(Consultas)); } }
    }

}
